import { useState, useCallback } from 'react';
import { Layout } from '@/components/layout/Layout';
import { Calendar } from '@/components/ui/Calendar';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/Card';
import { Button } from '@/components/ui/Button';
import { Input } from '@/components/ui/Input';
import { useAvailability, useBookingPrice } from '@/hooks/useBookings';
import { formatCurrency, formatDate, calculateNights } from '@/lib/utils';
import { CalendarDays, Users, CreditCard, AlertCircle, CheckCircle } from 'lucide-react';
import { supabase } from '@/integrations/supabase/client';

type BookingStep = 'dates' | 'details' | 'confirm';

export default function Booking() {
  const [step, setStep] = useState<BookingStep>('dates');
  const [checkIn, setCheckIn] = useState<Date | null>(null);
  const [checkOut, setCheckOut] = useState<Date | null>(null);
  const [selectingCheckOut, setSelectingCheckOut] = useState(false);
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [submitError, setSubmitError] = useState<string | null>(null);
  const [submitSuccess, setSubmitSuccess] = useState(false);

  const [formData, setFormData] = useState({
    firstName: '',
    lastName: '',
    email: '',
    phone: '',
    adults: 2,
    children: 0,
    message: ''
  });

  const { isDateBlocked, loading: availabilityLoading } = useAvailability();
  const { totalPrice, nights } = useBookingPrice(checkIn, checkOut);

  const handleDateSelect = useCallback((date: Date) => {
    if (!checkIn || selectingCheckOut) {
      if (!selectingCheckOut) {
        setCheckIn(date);
        setCheckOut(null);
        setSelectingCheckOut(true);
      } else {
        if (date > checkIn!) {
          setCheckOut(date);
          setSelectingCheckOut(false);
        } else {
          setCheckIn(date);
          setCheckOut(null);
        }
      }
    } else {
      setCheckIn(date);
      setCheckOut(null);
      setSelectingCheckOut(true);
    }
  }, [checkIn, selectingCheckOut]);

  const handleInputChange = (e: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement>) => {
    const { name, value } = e.target;
    setFormData((prev) => ({ ...prev, [name]: value }));
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!supabase || !checkIn || !checkOut) return;

    setIsSubmitting(true);
    setSubmitError(null);

    try {
      // First create customer
      const { data: customer, error: customerError } = await supabase.
      from('customers').
      insert({
        first_name: formData.firstName,
        last_name: formData.lastName,
        email: formData.email,
        phone: formData.phone || null
      }).
      select('id').
      single();

      if (customerError) throw customerError;

      // Then create booking
      const { error: bookingError } = await supabase.
      from('bookings').
      insert({
        customer_id: customer.id,
        booking_number: '', // Will be auto-generated by trigger
        check_in: checkIn.toISOString().split('T')[0],
        check_out: checkOut.toISOString().split('T')[0],
        guests_adults: formData.adults,
        guests_children: formData.children,
        total_price: totalPrice,
        deposit_amount: totalPrice * 0.3,
        status: 'pending',
        source: 'direct',
        special_requests: formData.message || null
      });

      if (bookingError) throw bookingError;

      setSubmitSuccess(true);
    } catch (err) {
      setSubmitError(err instanceof Error ? err.message : 'Ein Fehler ist aufgetreten');
    } finally {
      setIsSubmitting(false);
    }
  };

  if (submitSuccess) {
    return (
      <Layout>
        <div data-ev-id="ev_f954b1e4c3" className="max-w-2xl mx-auto px-4 py-20">
          <Card>
            <CardContent className="p-8 text-center">
              <CheckCircle className="w-16 h-16 text-success mx-auto mb-4" />
              <h1 data-ev-id="ev_7f3d90565a" className="text-2xl font-bold mb-2">Anfrage eingegangen!</h1>
              <p data-ev-id="ev_f413107a5b" className="text-muted-foreground mb-6">
                Vielen Dank! Ihre Buchungsanfrage wird nun von uns geprüft. 
                Sie erhalten innerhalb von 24 Stunden eine Bestätigung per E-Mail 
                mit Ihren Zugangsdaten zum Gästeportal.
              </p>
              <div data-ev-id="ev_6216b4cdaa" className="bg-muted/50 rounded-lg p-4 text-sm text-left">
                <p data-ev-id="ev_e07c371468" className="font-medium mb-2">So geht es weiter:</p>
                <ol data-ev-id="ev_dbb6fe4b29" className="list-decimal list-inside text-muted-foreground flex flex-col gap-1">
                  <li data-ev-id="ev_c037d04cf5">Wir prüfen Ihre Anfrage und die Verfügbarkeit</li>
                  <li data-ev-id="ev_a712038591">Sie erhalten eine Bestätigung mit Zugangsdaten</li>
                  <li data-ev-id="ev_3f0996281a">Im Gästeportal finden Sie Vertrag & alle Dokumente</li>
                </ol>
              </div>
              <p data-ev-id="ev_c06b1aa00f" className="text-sm text-muted-foreground">
                Gewünschter Zeitraum: {formatDate(checkIn!)} - {formatDate(checkOut!)}
              </p>
            </CardContent>
          </Card>
        </div>
      </Layout>);

  }

  return (
    <Layout>
      <div data-ev-id="ev_f835f88255" className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-12">
        <div data-ev-id="ev_89797c4e28" className="text-center mb-12">
          <h1 data-ev-id="ev_a65f9fe5f7" className="font-display text-3xl sm:text-4xl font-bold text-foreground mb-4">
            Verfügbarkeit & Buchung
          </h1>
          <p data-ev-id="ev_064419a4ba" className="text-muted-foreground max-w-2xl mx-auto">
            Wählen Sie Ihren Wunschzeitraum und senden Sie uns Ihre Anfrage
          </p>
        </div>

        <div data-ev-id="ev_0f446474b8" className="grid grid-cols-1 lg:grid-cols-3 gap-8">
          {/* Calendar */}
          <div data-ev-id="ev_90d052b188" className="lg:col-span-2">
            <Card>
              <CardHeader>
                <CardTitle className="flex items-center gap-2">
                  <CalendarDays className="w-5 h-5 text-primary" />
                  Verfügbarkeitskalender
                </CardTitle>
              </CardHeader>
              <CardContent>
                {availabilityLoading ?
                <div data-ev-id="ev_fe8eac17a6" className="h-80 flex items-center justify-center">
                    <div data-ev-id="ev_7810405e88" className="animate-pulse text-muted-foreground">Kalender wird geladen...</div>
                  </div> :

                <>
                    <p data-ev-id="ev_6a9b3ae45c" className="text-sm text-muted-foreground mb-4">
                      {!checkIn ? 'Wählen Sie Ihr Anreisedatum' :
                    selectingCheckOut ? 'Wählen Sie Ihr Abreisedatum' :
                    'Zeitraum ausgewählt'}
                    </p>
                    <Calendar
                    selectedStart={checkIn}
                    selectedEnd={checkOut}
                    onSelectDate={handleDateSelect}
                    isDateBlocked={isDateBlocked} />

                  </>
                }
              </CardContent>
            </Card>
          </div>

          {/* Booking Summary & Form */}
          <div data-ev-id="ev_33f889ac04" className="flex flex-col gap-6">
            {/* Summary Card */}
            <Card>
              <CardHeader>
                <CardTitle>Ihre Auswahl</CardTitle>
              </CardHeader>
              <CardContent className="flex flex-col gap-4">
                <div data-ev-id="ev_d382ce4cec" className="flex justify-between">
                  <span data-ev-id="ev_eb5ebe3982" className="text-muted-foreground">Anreise:</span>
                  <span data-ev-id="ev_83364e5daa" className="font-medium">
                    {checkIn ? formatDate(checkIn) : '-- . -- . ----'}
                  </span>
                </div>
                <div data-ev-id="ev_2812164986" className="flex justify-between">
                  <span data-ev-id="ev_c7b2c28748" className="text-muted-foreground">Abreise:</span>
                  <span data-ev-id="ev_9512e462ac" className="font-medium">
                    {checkOut ? formatDate(checkOut) : '-- . -- . ----'}
                  </span>
                </div>
                <hr data-ev-id="ev_5568d2db4b" className="border-border" />
                <div data-ev-id="ev_b32ef141a0" className="flex justify-between">
                  <span data-ev-id="ev_e1edd2c5fb" className="text-muted-foreground">Nächte:</span>
                  <span data-ev-id="ev_c3b8646d3f" className="font-medium">{nights || '-'}</span>
                </div>
                <div data-ev-id="ev_9e450283d1" className="flex justify-between text-lg">
                  <span data-ev-id="ev_08595997ea" className="font-semibold">Gesamtpreis:</span>
                  <span data-ev-id="ev_7319b9da6d" className="font-bold text-primary">
                    {totalPrice > 0 ? formatCurrency(totalPrice) : '-'}
                  </span>
                </div>
                {totalPrice > 0 &&
                <p data-ev-id="ev_220a8c7f1f" className="text-xs text-muted-foreground">
                    Anzahlung: {formatCurrency(totalPrice * 0.3)} (30%)
                  </p>
                }
              </CardContent>
            </Card>

            {/* Booking Form */}
            {checkIn && checkOut &&
            <Card>
                <CardHeader>
                  <CardTitle className="flex items-center gap-2">
                    <Users className="w-5 h-5 text-primary" />
                    Ihre Daten
                  </CardTitle>
                </CardHeader>
                <CardContent>
                  <form data-ev-id="ev_415a3bd2b2" onSubmit={handleSubmit} className="flex flex-col gap-4">
                    <div data-ev-id="ev_644f9f5bf6" className="grid grid-cols-2 gap-4">
                      <Input
                      label="Vorname"
                      name="firstName"
                      value={formData.firstName}
                      onChange={handleInputChange}
                      required />

                      <Input
                      label="Nachname"
                      name="lastName"
                      value={formData.lastName}
                      onChange={handleInputChange}
                      required />

                    </div>
                    <Input
                    label="E-Mail"
                    name="email"
                    type="email"
                    value={formData.email}
                    onChange={handleInputChange}
                    required />

                    <Input
                    label="Telefon (optional)"
                    name="phone"
                    type="tel"
                    value={formData.phone}
                    onChange={handleInputChange} />

                    <div data-ev-id="ev_dcba03f2b7" className="grid grid-cols-2 gap-4">
                      <Input
                      label="Erwachsene"
                      name="adults"
                      type="number"
                      min={1}
                      max={6}
                      value={formData.adults}
                      onChange={handleInputChange} />

                      <Input
                      label="Kinder"
                      name="children"
                      type="number"
                      min={0}
                      max={4}
                      value={formData.children}
                      onChange={handleInputChange} />

                    </div>
                    <div data-ev-id="ev_4539d2b005" className="flex flex-col gap-1.5">
                      <label data-ev-id="ev_36c749764d" htmlFor="message" className="text-sm font-medium">Nachricht (optional)</label>
                      <textarea data-ev-id="ev_07e3ca8a2f"
                    id="message"
                    name="message"
                    rows={3}
                    value={formData.message}
                    onChange={handleInputChange}
                    className="w-full rounded-md border border-input bg-background px-3 py-2 text-sm placeholder:text-muted-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring"
                    placeholder="Besondere Wünsche oder Fragen..." />

                    </div>

                    {submitError &&
                  <div data-ev-id="ev_cf7936274a" className="flex items-center gap-2 text-sm text-destructive bg-destructive/10 p-3 rounded-md">
                        <AlertCircle className="w-4 h-4 flex-shrink-0" />
                        <span data-ev-id="ev_a86b0c5d1f">{submitError}</span>
                      </div>
                  }

                    <Button type="submit" disabled={isSubmitting} className="w-full gap-2">
                      <CreditCard className="w-4 h-4" />
                      {isSubmitting ? 'Wird gesendet...' : 'Unverbindlich anfragen'}
                    </Button>

                    <p data-ev-id="ev_ee21b89ba4" className="text-xs text-muted-foreground text-center">
                      🔒 Unverbindliche Anfrage – Sie gehen keine Verpflichtung ein. 
                      Erst nach unserer Bestätigung und Ihrer Anzahlung wird die Buchung verbindlich.
                    </p>
                  </form>
                </CardContent>
              </Card>
            }
          </div>
        </div>
      </div>
    </Layout>);

}